# Generated by Django 5.2.9 on 2026-02-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
